[[redirects]]
  from = "/backend/*"
  to = "http://gate.issuemoa.kr:38000/:splat"  
  status = 200
  force = true

[[redirects]]
  from = "/kakao/*"
  to = "https://kauth.kakao.com/:splat"  
  status = 200
  force = true

[[redirects]]
  from = "/kapi/*"
  to = "https://kapi.kakao.com/:splat"  
  status = 200
  force = true

[[redirects]]
  from = "/weather-api/*"
  to = "https://api.openweathermap.org/data/2.5/:splat"  
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200